version: '3'
services:
  mylaba:
    image: "mysql:latest"
    volumes:
      - /var/lib/docker/volumes/mysql-db:/var/lib/mysql-db
    environment:
      - MYSQL_DATABASE=leszczynski
      - MYSQL_ROOT_PASSWORD=P4r4d0x!
      - MYSQL_HOST=mylaba
      - MYSQL_USER=maxroot
      - MYSQL_PASSWORD=P4r4d0x!
  havonagila:
    image: "ubuntu:bionic"
    restart: on-failure
    depends_on:
      - mylaba
    environment:
      - DATABASE_HOST=mylaba
      - DATABASE_USER=maxroot
      - DATABASE_PASSWORD=P4r4d0x!
      - DATABASE_NAME=leszczynski
      - DATABASE_PORT=3306
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - 8080:8080
      - 9090:9090
      - 9100:9100
